<?php
/**
 * Royal Plugins Chrome Pack — Royal MCP edition.
 *
 * Renders the family-wide admin chrome on every Royal MCP admin surface:
 *   1. Custom top header (logo + wordmark + View Docs / Support buttons)
 *   2. Lightweight footer (Royal Plugins family links + version marker)
 *   3. Royal Tools submenu page (5-card grid of free Royal Plugins family members)
 *   4. Founders Bundle callout on the Royal Tools page
 *
 * Screen-ID-gated to Royal MCP admin pages only — never touches other WP admin.
 *
 * Design source of truth: _internal/_shared/CHROME_PACK.md
 *
 * @package Royal_MCP
 */

namespace Royal_MCP\Chrome;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Royal_MCP_Chrome {

    const ROYAL_TOOLS_MENU_SLUG        = 'royal-mcp-tools';
    const FOUNDERS_DISMISS_USER_META   = 'royal_plugins_dismissed_founders_callout';
    const FOUNDERS_DISMISS_ACTION      = 'royal_mcp_dismiss_founders_callout';
    const CSS_HANDLE                   = 'royal-mcp-chrome';
    const BODY_CLASS                   = 'royal-mcp-chrome-scope';

    /** @var self|null */
    private static $instance = null;

    public static function get_instance(): self {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action( 'admin_menu',            [ $this, 'register_royal_tools_menu' ], 20 );
        add_action( 'in_admin_header',       [ $this, 'render_top_header' ] );
        add_filter( 'admin_footer_text',     [ $this, 'filter_admin_footer_text' ], 999 );
        add_filter( 'update_footer',         [ $this, 'filter_update_footer' ], 999 );
        add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_assets' ] );
        add_filter( 'admin_body_class',      [ $this, 'filter_admin_body_class' ] );
        add_action( 'admin_post_' . self::FOUNDERS_DISMISS_ACTION, [ $this, 'handle_founders_dismiss' ] );
    }

    /* ==================================================================
     *  Screen-ID gate
     * ================================================================ */

    /**
     * True on any Royal MCP admin page (Settings, Activity Log, Royal Tools,
     * License, Wizard, etc.). Screen IDs generated by WP follow the shape
     * `toplevel_page_royal-mcp` for the parent menu, and
     * `royal-mcp_page_<submenu-slug>` for submenus.
     */
    public function is_royal_mcp_admin_page(): bool {
        if ( ! function_exists( 'get_current_screen' ) ) {
            return false;
        }
        $screen = get_current_screen();
        if ( ! $screen || empty( $screen->id ) ) {
            return false;
        }
        $id = (string) $screen->id;
        return false !== strpos( $id, 'royal-mcp' )
            || false !== strpos( $id, 'royal_mcp' );
    }

    /* ==================================================================
     *  Assets
     * ================================================================ */

    public function enqueue_assets(): void {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return;
        }
        $rel_path = 'assets/css/chrome.css';
        $abs_path = ROYAL_MCP_PLUGIN_DIR . $rel_path;
        $version  = defined( 'ROYAL_MCP_VERSION' ) ? ROYAL_MCP_VERSION : '1.0.0';
        if ( file_exists( $abs_path ) ) {
            $version .= '.' . filemtime( $abs_path );
        }
        wp_enqueue_style(
            self::CSS_HANDLE,
            ROYAL_MCP_PLUGIN_URL . $rel_path,
            [],
            $version
        );
    }

    public function filter_admin_body_class( $classes ) {
        if ( $this->is_royal_mcp_admin_page() ) {
            $classes .= ' ' . self::BODY_CLASS . ' ';
        }
        return $classes;
    }

    /* ==================================================================
     *  1. Custom top header
     * ================================================================ */

    public function render_top_header(): void {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return;
        }
        $docs_url    = 'https://royalplugins.com/support/royal-mcp/';
        $support_url = 'https://wordpress.org/support/plugin/royal-mcp/';
        ?>
        <div class="royal-mcp-chrome-header">
            <div class="royal-mcp-chrome-header-brand">
                <div class="royal-mcp-chrome-logo" aria-hidden="true">R</div>
                <span class="royal-mcp-chrome-wordmark"><?php esc_html_e( 'Royal MCP', 'royal-mcp' ); ?></span>
            </div>
            <div class="royal-mcp-chrome-header-actions">
                <a href="<?php echo esc_url( $docs_url ); ?>" class="royal-mcp-chrome-header-btn" target="_blank" rel="noopener noreferrer">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
                    <?php esc_html_e( 'View Docs', 'royal-mcp' ); ?>
                </a>
                <a href="<?php echo esc_url( $support_url ); ?>" class="royal-mcp-chrome-header-btn" target="_blank" rel="noopener noreferrer">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                    <?php esc_html_e( 'Support', 'royal-mcp' ); ?>
                </a>
            </div>
        </div>
        <?php
    }

    /* ==================================================================
     *  2. Lightweight footer
     * ================================================================ */

    public function filter_admin_footer_text( $text ) {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return $text;
        }
        ob_start();
        ?>
        <span class="royal-mcp-chrome-footer">
            <span><?php esc_html_e( 'Royal Plugins', 'royal-mcp' ); ?></span>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://royalplugins.com/blog/" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Blog', 'royal-mcp' ); ?></a>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://www.youtube.com/@royalplugins" target="_blank" rel="noopener noreferrer">
                <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M23.5 6.2s-.2-1.6-.9-2.3c-.9-.9-1.9-.9-2.4-1C16.7 2.6 12 2.6 12 2.6s-4.7 0-8.2.3c-.5.1-1.5.1-2.4 1-.7.7-.9 2.3-.9 2.3S.3 8.1.3 10v1.8c0 1.9.2 3.8.2 3.8s.2 1.6.9 2.3c.9.9 2.1.9 2.6 1 1.9.2 8 .3 8 .3s4.7 0 8.2-.3c.5-.1 1.5-.1 2.4-1 .7-.7.9-2.3.9-2.3s.2-1.9.2-3.8V10c0-1.9-.2-3.8-.2-3.8zM9.5 14.3V7.5l6.2 3.4-6.2 3.4z"/></svg>
                <?php esc_html_e( 'YouTube', 'royal-mcp' ); ?>
            </a>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://github.com/royalplugins" target="_blank" rel="noopener noreferrer">
                <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .3a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2c-3.3.7-4-1.6-4-1.6-.6-1.4-1.4-1.8-1.4-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.9 1.2 1.9 1.2 1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.2 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.7 1.7.2 2.9.1 3.2.8.8 1.2 1.9 1.2 3.2 0 4.6-2.8 5.6-5.5 5.9.5.4.9 1.1.9 2.3v3.3c0 .3.2.7.8.6A12 12 0 0 0 12 .3"/></svg>
                <?php esc_html_e( 'GitHub', 'royal-mcp' ); ?>
            </a>
        </span>
        <?php
        return (string) ob_get_clean();
    }

    public function filter_update_footer( $content ) {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return $content;
        }
        $version = defined( 'ROYAL_MCP_VERSION' ) ? ROYAL_MCP_VERSION : '';
        return sprintf(
            /* translators: %s: plugin version */
            esc_html__( 'Royal MCP v%s', 'royal-mcp' ),
            esc_html( $version )
        );
    }

    /* ==================================================================
     *  3. Royal Tools submenu page
     * ================================================================ */

    public function register_royal_tools_menu(): void {
        add_submenu_page(
            'royal-mcp',
            __( 'Royal Tools', 'royal-mcp' ),
            __( 'Royal Tools', 'royal-mcp' ),
            'manage_options',
            self::ROYAL_TOOLS_MENU_SLUG,
            [ $this, 'render_royal_tools_page' ]
        );
    }

    public function render_royal_tools_page(): void {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( esc_html__( 'You do not have permission to view Royal Tools.', 'royal-mcp' ) );
        }
        $family      = $this->get_family_plugins_with_state();
        $show_bundle = ! $this->founders_callout_dismissed();
        ?>
        <div class="wrap royal-mcp-tools-wrap">
            <div class="royal-mcp-tools-title-row">
                <div>
                    <h1 class="royal-mcp-tools-title"><?php esc_html_e( 'Royal Tools', 'royal-mcp' ); ?></h1>
                    <p class="royal-mcp-tools-subtitle"><?php esc_html_e( 'Free WordPress plugins from Royal Plugins — one-click install, no signup.', 'royal-mcp' ); ?></p>
                </div>
            </div>

            <?php if ( $show_bundle ) : ?>
                <?php $this->render_founders_callout(); ?>
            <?php endif; ?>

            <div class="royal-mcp-tools-section-head">
                <h2><?php esc_html_e( 'Free companion plugins', 'royal-mcp' ); ?></h2>
                <p><?php esc_html_e( 'All available on WordPress.org. Every feature ships free.', 'royal-mcp' ); ?></p>
            </div>

            <div class="royal-mcp-tools-grid">
                <?php foreach ( $family as $slug => $plugin ) : ?>
                    <?php $this->render_plugin_card( $slug, $plugin ); ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php
    }

    /* ==================================================================
     *  4. Founders Bundle callout
     * ================================================================ */

    private function render_founders_callout(): void {
        $dismiss_url = wp_nonce_url(
            admin_url( 'admin-post.php?action=' . self::FOUNDERS_DISMISS_ACTION ),
            self::FOUNDERS_DISMISS_ACTION
        );
        ?>
        <div class="royal-mcp-founders">
            <div class="royal-mcp-founders-crown" aria-hidden="true">&#128081;</div>
            <div class="royal-mcp-founders-body">
                <h3>
                    <?php
                    printf(
                        /* translators: %s: gold-highlighted "$49/yr" text */
                        esc_html__( 'All 6 Pro plugins from %s — Founders Bundle', 'royal-mcp' ),
                        '<span class="gold">' . esc_html__( '$49/yr', 'royal-mcp' ) . '</span>'
                    );
                    ?>
                </h3>
                <p>
                    <?php
                    echo esc_html__(
                        'GuardPress Pro · SiteVault Pro · ForgeCache · SEObolt Pro · Royal Affiliate Pro · FormForge Pro. 12 tiers, 200 seats total. Each tier that sells out, the price goes up — but whatever tier you land on is your renewal rate forever.',
                        'royal-mcp'
                    );
                    ?>
                </p>
            </div>
            <a href="https://royalplugins.com/founders/" target="_blank" rel="noopener noreferrer" class="royal-mcp-founders-cta">
                <?php esc_html_e( 'See live tiers &rarr;', 'royal-mcp' ); ?>
            </a>
            <a href="<?php echo esc_url( $dismiss_url ); ?>" class="royal-mcp-founders-dismiss" title="<?php esc_attr_e( 'Dismiss this bundle callout', 'royal-mcp' ); ?>" aria-label="<?php esc_attr_e( 'Dismiss this bundle callout', 'royal-mcp' ); ?>">&times;</a>
        </div>
        <?php
    }

    private function founders_callout_dismissed(): bool {
        $user_id = get_current_user_id();
        if ( ! $user_id ) {
            return false;
        }
        return (bool) get_user_meta( $user_id, self::FOUNDERS_DISMISS_USER_META, true );
    }

    public function handle_founders_dismiss(): void {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( esc_html__( 'You do not have permission to dismiss this notice.', 'royal-mcp' ) );
        }
        check_admin_referer( self::FOUNDERS_DISMISS_ACTION );
        update_user_meta( get_current_user_id(), self::FOUNDERS_DISMISS_USER_META, 1 );
        wp_safe_redirect( wp_get_referer() ?: admin_url( 'admin.php?page=' . self::ROYAL_TOOLS_MENU_SLUG ) );
        exit;
    }

    /* ==================================================================
     *  Family plugin registry
     * ================================================================ */

    private function get_family_plugins(): array {
        return [
            'royal-ai-firewall' => [
                'name'        => __( 'Royal AI Firewall', 'royal-mcp' ),
                'basename'    => 'royal-ai-firewall/royal-ai-firewall.php',
                'icon'        => '&#128737;',
                'search_slug' => 'royal-ai-firewall',
                'learn_url'   => 'https://royalplugins.com/royal-ai-firewall/',
                'pitch'       => __( 'See every AI agent hitting your site and decide who gets in. Blocks GPTBot, ClaudeBot, PerplexityBot and 60+ others at the WordPress layer.', 'royal-mcp' ),
            ],
            'royal-mcp' => [
                'name'        => __( 'Royal MCP', 'royal-mcp' ),
                'basename'    => 'royal-mcp/royal-mcp.php',
                'icon'        => '&#128268;',
                'search_slug' => 'royal-mcp',
                'learn_url'   => 'https://royalplugins.com/royal-mcp/',
                'pitch'       => __( 'Connect Claude, ChatGPT, and Cursor directly to your WordPress site via MCP. Full-stack tools for AI-driven content and store management.', 'royal-mcp' ),
            ],
            'sitevault' => [
                'name'        => __( 'SiteVault Lite', 'royal-mcp' ),
                'basename'    => 'sitevault-backup-restore-migration/sitevault.php',
                'icon'        => '&#128190;',
                'search_slug' => 'sitevault backup',
                'learn_url'   => 'https://royalplugins.com/sitevault-lite/',
                'pitch'       => __( 'Full-site backup, restore, and migration in your WordPress admin. WP-CLI commands for automation. No cloud upsell, no seat limits.', 'royal-mcp' ),
            ],
            'royal-access' => [
                'name'        => __( 'Royal Access', 'royal-mcp' ),
                'basename'    => 'royal-access/royal-access.php',
                'icon'        => '&#9855;',
                'search_slug' => 'royal-access',
                'learn_url'   => 'https://royalplugins.com/royal-access/',
                'pitch'       => __( 'Accessibility toolbar, contrast checker, and WCAG-fix suggestions for your WordPress site. Every setting free.', 'royal-mcp' ),
            ],
            'royal-links' => [
                'name'        => __( 'Royal Links', 'royal-mcp' ),
                'basename'    => 'royal-links/royal-links.php',
                'icon'        => '&#128279;',
                'search_slug' => 'royal-links',
                'learn_url'   => 'https://royalplugins.com/royal-links/',
                'pitch'       => __( 'Link cloaking, click tracking, geo-targeting, A/B testing, QR codes, and 404 redirect manager.', 'royal-mcp' ),
            ],
        ];
    }

    /**
     * Registry + per-card state (you're here / active / installed-inactive /
     * not installed). Loaded once per page render.
     */
    public function get_family_plugins_with_state(): array {
        if ( ! function_exists( 'get_plugins' ) ) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }
        $all_installed = array_keys( get_plugins() );
        $out           = $this->get_family_plugins();
        $current       = defined( 'ROYAL_MCP_PLUGIN_BASENAME' ) ? ROYAL_MCP_PLUGIN_BASENAME : 'royal-mcp/royal-mcp.php';
        foreach ( $out as $slug => &$plugin ) {
            if ( $plugin['basename'] === $current ) {
                $plugin['state'] = 'here';
            } elseif ( in_array( $plugin['basename'], $all_installed, true ) && is_plugin_active( $plugin['basename'] ) ) {
                $plugin['state'] = 'active';
            } elseif ( in_array( $plugin['basename'], $all_installed, true ) ) {
                $plugin['state'] = 'inactive';
            } else {
                $plugin['state'] = 'not_installed';
            }
        }
        return $out;
    }

    private function render_plugin_card( string $slug, array $plugin ): void {
        $state       = $plugin['state'] ?? 'not_installed';
        $card_class  = 'royal-mcp-tools-card';
        if ( 'here' === $state ) {
            $card_class .= ' royal-mcp-tools-card--here';
        } elseif ( 'active' === $state ) {
            $card_class .= ' royal-mcp-tools-card--active';
        }
        ?>
        <div class="<?php echo esc_attr( $card_class ); ?>">
            <div class="royal-mcp-tools-card-head">
                <div class="royal-mcp-tools-card-icon" aria-hidden="true"><?php echo wp_kses_post( $plugin['icon'] ); ?></div>
                <?php $this->render_card_badge( $state ); ?>
            </div>
            <h3><?php echo esc_html( $plugin['name'] ); ?></h3>
            <p><?php echo esc_html( $plugin['pitch'] ); ?></p>
            <div class="royal-mcp-tools-card-actions">
                <?php $this->render_card_actions( $slug, $plugin ); ?>
            </div>
        </div>
        <?php
    }

    private function render_card_badge( string $state ): void {
        if ( 'here' === $state ) {
            echo '<span class="royal-mcp-tools-card-badge">' . esc_html__( 'You\'re here', 'royal-mcp' ) . '</span>';
        } elseif ( 'active' === $state ) {
            echo '<span class="royal-mcp-tools-card-badge">' . esc_html__( '✓ Active', 'royal-mcp' ) . '</span>';
        } else {
            echo '<span class="royal-mcp-tools-card-badge royal-mcp-tools-card-badge--free">' . esc_html__( 'FREE', 'royal-mcp' ) . '</span>';
        }
    }

    private function render_card_actions( string $slug, array $plugin ): void {
        $state = $plugin['state'] ?? 'not_installed';
        if ( 'here' === $state ) {
            echo '<div class="royal-mcp-tools-badge-active">' . esc_html__( 'You\'re here', 'royal-mcp' ) . '</div>';
            return;
        }
        if ( 'active' === $state ) {
            echo '<div class="royal-mcp-tools-badge-active">' . esc_html__( '✓ Active', 'royal-mcp' ) . '</div>';
            return;
        }
        if ( 'inactive' === $state ) {
            $activate_url = wp_nonce_url(
                admin_url( 'plugins.php?action=activate&plugin=' . urlencode( $plugin['basename'] ) ),
                'activate-plugin_' . $plugin['basename']
            );
            printf(
                '<a href="%1$s" class="royal-mcp-tools-btn-activate">%2$s</a><a href="%3$s" target="_blank" rel="noopener noreferrer" class="royal-mcp-tools-btn-learn">%4$s</a>',
                esc_url( $activate_url ),
                esc_html__( 'Activate', 'royal-mcp' ),
                esc_url( $plugin['learn_url'] ),
                esc_html__( 'Learn', 'royal-mcp' )
            );
            return;
        }
        $install_url = admin_url(
            'plugin-install.php?s=' . rawurlencode( $plugin['search_slug'] ) . '&tab=search&type=term'
        );
        printf(
            '<a href="%1$s" class="royal-mcp-tools-btn-install">%2$s</a><a href="%3$s" target="_blank" rel="noopener noreferrer" class="royal-mcp-tools-btn-learn">%4$s</a>',
            esc_url( $install_url ),
            esc_html__( 'Install', 'royal-mcp' ),
            esc_url( $plugin['learn_url'] ),
            esc_html__( 'Learn', 'royal-mcp' )
        );
    }
}
