<?php
/**
 * Royal Plugins Chrome Pack — Royal MCP edition.
 *
 * Renders the family-wide admin chrome on every Royal MCP admin surface:
 *   1. Custom top header (logo + wordmark + View Docs / Support buttons)
 *   2. Lightweight footer (Royal Plugins family links + version marker)
 *   3. Royal Tools submenu page (5-card grid of free Royal Plugins family members)
 *
 * Screen-ID-gated to Royal MCP admin pages only — never touches other WP admin.
 *
 * @package Royal_MCP
 */

namespace Royal_MCP\Chrome;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Royal_MCP_Chrome {

    const ROYAL_TOOLS_MENU_SLUG        = 'royal-mcp-tools';
    const CSS_HANDLE                   = 'royal-mcp-chrome';
    const BODY_CLASS                   = 'royal-mcp-chrome-scope';

    // Royal MCP Pro launch — hardcoded date + waitlist URL. Date-aware content
    // in the Chrome card + admin notice + submenu label switches automatically
    // on/after this date. If the launch date changes, update this constant and
    // all three surfaces flip in one commit.
    const PRO_LAUNCH_DATE              = '2026-08-11';
    const PRO_WAITLIST_URL_BASE        = 'https://royalplugins.com/royal-mcp-pro/founding-members/';
    const PRO_POST_LAUNCH_URL_BASE     = 'https://royalplugins.com/royal-mcp-pro/';
    const FM_NOTICE_DISMISS_META       = 'royal_mcp_founding_members_notice_dismissed';
    const PRO_LAUNCH_NOTICE_DISMISS_META = 'royal_mcp_pro_launch_notice_dismissed';
    const FM_NOTICE_DISMISS_ACTION     = 'royal_mcp_dismiss_founding_members_notice';
    const FM_MENU_SLUG                 = 'royal-mcp-pro-external';

    /** @var self|null */
    private static $instance = null;

    public static function get_instance(): self {
        if ( null === self::$instance ) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {
        add_action( 'admin_menu',            [ $this, 'register_royal_tools_menu' ], 20 );
        add_action( 'in_admin_header',       [ $this, 'render_top_header' ] );
        add_filter( 'admin_footer_text',     [ $this, 'filter_admin_footer_text' ], 999 );
        add_filter( 'update_footer',         [ $this, 'filter_update_footer' ], 999 );
        add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_assets' ] );
        add_filter( 'admin_body_class',      [ $this, 'filter_admin_body_class' ] );

        // Founders-waitlist promo surfaces (submenu item, admin notice, dismiss
        // handler, target=_blank injector) only make sense on standalone Free.
        // When running vendored inside Royal MCP Pro, Pro customers are already
        // past the funnel — skip the entire promo path.
        if ( ! defined( 'ROYAL_MCP_LOADED_BY_PRO' ) ) {
            add_action( 'admin_menu',            [ $this, 'register_founding_members_menu' ], 21 );
            add_action( 'admin_post_' . self::FM_NOTICE_DISMISS_ACTION, [ $this, 'handle_founding_members_dismiss' ] );
            add_action( 'admin_notices',         [ $this, 'render_founding_members_notice' ] );
            add_action( 'admin_enqueue_scripts', [ $this, 'inject_founding_members_menu_target_blank' ], 100 );
        }
    }

    /* ==================================================================
     *  Screen-ID gate
     * ================================================================ */

    /**
     * True on any Royal MCP admin page (Settings, Activity Log, Royal Tools,
     * License, Wizard, etc.). Screen IDs generated by WP follow the shape
     * `toplevel_page_royal-mcp` for the parent menu, and
     * `royal-mcp_page_<submenu-slug>` for submenus.
     */
    public function is_royal_mcp_admin_page(): bool {
        if ( ! function_exists( 'get_current_screen' ) ) {
            return false;
        }
        $screen = get_current_screen();
        if ( ! $screen || empty( $screen->id ) ) {
            return false;
        }
        $id = (string) $screen->id;
        return false !== strpos( $id, 'royal-mcp' )
            || false !== strpos( $id, 'royal_mcp' );
    }

    /* ==================================================================
     *  Assets
     * ================================================================ */

    public function enqueue_assets(): void {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return;
        }
        $rel_path = 'assets/css/chrome.css';
        $abs_path = ROYAL_MCP_PLUGIN_DIR . $rel_path;
        $version  = defined( 'ROYAL_MCP_VERSION' ) ? ROYAL_MCP_VERSION : '1.0.0';
        if ( file_exists( $abs_path ) ) {
            $version .= '.' . filemtime( $abs_path );
        }
        wp_enqueue_style(
            self::CSS_HANDLE,
            ROYAL_MCP_PLUGIN_URL . $rel_path,
            [],
            $version
        );
    }

    public function filter_admin_body_class( $classes ) {
        if ( $this->is_royal_mcp_admin_page() ) {
            $classes .= ' ' . self::BODY_CLASS . ' ';
        }
        return $classes;
    }

    /* ==================================================================
     *  1. Custom top header
     * ================================================================ */

    public function render_top_header(): void {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return;
        }
        // Filters let a child plugin (Royal MCP Pro, when it loads this Free
        // codebase vendored) override the wordmark + external links so its
        // admin chrome carries the paid-tier branding instead of the free-
        // plugin defaults.
        $wordmark    = apply_filters( 'royal_mcp_chrome_wordmark', __( 'Royal MCP', 'royal-mcp' ) );
        $docs_url    = apply_filters( 'royal_mcp_chrome_docs_url', 'https://royalplugins.com/support/royal-mcp/' );
        $support_url = apply_filters( 'royal_mcp_chrome_support_url', 'https://wordpress.org/support/plugin/royal-mcp/' );
        ?>
        <div class="royal-mcp-chrome-header">
            <div class="royal-mcp-chrome-header-brand">
                <div class="royal-mcp-chrome-logo" aria-hidden="true">R</div>
                <span class="royal-mcp-chrome-wordmark"><?php echo esc_html( $wordmark ); ?></span>
            </div>
            <div class="royal-mcp-chrome-header-actions">
                <a href="<?php echo esc_url( $docs_url ); ?>" class="royal-mcp-chrome-header-btn" target="_blank" rel="noopener noreferrer">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>
                    <?php esc_html_e( 'View Docs', 'royal-mcp' ); ?>
                </a>
                <a href="<?php echo esc_url( $support_url ); ?>" class="royal-mcp-chrome-header-btn" target="_blank" rel="noopener noreferrer">
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
                    <?php esc_html_e( 'Support', 'royal-mcp' ); ?>
                </a>
            </div>
        </div>
        <?php
    }

    /* ==================================================================
     *  2. Lightweight footer
     * ================================================================ */

    public function filter_admin_footer_text( $text ) {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return $text;
        }
        ob_start();
        ?>
        <span class="royal-mcp-chrome-footer">
            <span><?php esc_html_e( 'Royal Plugins', 'royal-mcp' ); ?></span>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://royalplugins.com/blog/" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Blog', 'royal-mcp' ); ?></a>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://www.youtube.com/@royalplugins" target="_blank" rel="noopener noreferrer">
                <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M23.5 6.2s-.2-1.6-.9-2.3c-.9-.9-1.9-.9-2.4-1C16.7 2.6 12 2.6 12 2.6s-4.7 0-8.2.3c-.5.1-1.5.1-2.4 1-.7.7-.9 2.3-.9 2.3S.3 8.1.3 10v1.8c0 1.9.2 3.8.2 3.8s.2 1.6.9 2.3c.9.9 2.1.9 2.6 1 1.9.2 8 .3 8 .3s4.7 0 8.2-.3c.5-.1 1.5-.1 2.4-1 .7-.7.9-2.3.9-2.3s.2-1.9.2-3.8V10c0-1.9-.2-3.8-.2-3.8zM9.5 14.3V7.5l6.2 3.4-6.2 3.4z"/></svg>
                <?php esc_html_e( 'YouTube', 'royal-mcp' ); ?>
            </a>
            <span class="royal-mcp-chrome-footer-sep">·</span>
            <a href="https://github.com/royalplugins" target="_blank" rel="noopener noreferrer">
                <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .3a12 12 0 0 0-3.8 23.4c.6.1.8-.3.8-.6v-2c-3.3.7-4-1.6-4-1.6-.6-1.4-1.4-1.8-1.4-1.8-1.1-.7.1-.7.1-.7 1.2.1 1.9 1.2 1.9 1.2 1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.8-1.6-2.7-.3-5.5-1.3-5.5-6 0-1.3.5-2.4 1.2-3.2-.1-.3-.5-1.5.1-3.2 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0c2.3-1.5 3.3-1.2 3.3-1.2.7 1.7.2 2.9.1 3.2.8.8 1.2 1.9 1.2 3.2 0 4.6-2.8 5.6-5.5 5.9.5.4.9 1.1.9 2.3v3.3c0 .3.2.7.8.6A12 12 0 0 0 12 .3"/></svg>
                <?php esc_html_e( 'GitHub', 'royal-mcp' ); ?>
            </a>
        </span>
        <?php
        return (string) ob_get_clean();
    }

    public function filter_update_footer( $content ) {
        if ( ! $this->is_royal_mcp_admin_page() ) {
            return $content;
        }
        // Filters let child plugins (Royal MCP Pro) inject their own display
        // name + version into the admin footer stamp.
        $wordmark = apply_filters( 'royal_mcp_chrome_wordmark', __( 'Royal MCP', 'royal-mcp' ) );
        $version  = apply_filters(
            'royal_mcp_chrome_version',
            defined( 'ROYAL_MCP_VERSION' ) ? ROYAL_MCP_VERSION : ''
        );
        return sprintf(
            /* translators: 1: plugin display name, 2: plugin version */
            esc_html__( '%1$s v%2$s', 'royal-mcp' ),
            esc_html( $wordmark ),
            esc_html( $version )
        );
    }

    /* ==================================================================
     *  3. Royal Tools submenu page
     * ================================================================ */

    public function register_royal_tools_menu(): void {
        add_submenu_page(
            'royal-mcp',
            __( 'Royal Tools', 'royal-mcp' ),
            __( 'Royal Tools', 'royal-mcp' ),
            'manage_options',
            self::ROYAL_TOOLS_MENU_SLUG,
            [ $this, 'render_royal_tools_page' ]
        );
    }

    public function render_royal_tools_page(): void {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( esc_html__( 'You do not have permission to view Royal Tools.', 'royal-mcp' ) );
        }
        $family = $this->get_family_plugins_with_state();
        ?>
        <div class="wrap royal-mcp-tools-wrap">
            <div class="royal-mcp-tools-title-row">
                <div>
                    <h1 class="royal-mcp-tools-title"><?php echo esc_html( apply_filters( 'royal_mcp_chrome_tools_page_title', __( 'Royal Tools', 'royal-mcp' ) ) ); ?></h1>
                    <p class="royal-mcp-tools-subtitle"><?php echo esc_html( apply_filters( 'royal_mcp_chrome_tools_page_subtitle', __( 'Free WordPress plugins from Royal Plugins — one-click install, no signup.', 'royal-mcp' ) ) ); ?></p>
                </div>
            </div>

            <?php if ( defined( 'ROYAL_MCP_LOADED_BY_PRO' ) ) : ?>
                <?php \Royal_MCP\Admin\Settings_Page::render_founders_banner( true ); ?>
            <?php endif; ?>

            <div class="royal-mcp-tools-section-head">
                <h2><?php echo esc_html( apply_filters( 'royal_mcp_chrome_tools_section_heading', __( 'Free companion plugins', 'royal-mcp' ) ) ); ?></h2>
                <p><?php echo esc_html( apply_filters( 'royal_mcp_chrome_tools_section_subheading', __( 'All available on WordPress.org. Every feature ships free.', 'royal-mcp' ) ) ); ?></p>
            </div>

            <div class="royal-mcp-tools-grid">
                <?php foreach ( $family as $slug => $plugin ) : ?>
                    <?php $this->render_plugin_card( $slug, $plugin ); ?>
                <?php endforeach; ?>
            </div>

            <?php if ( ! defined( 'ROYAL_MCP_LOADED_BY_PRO' ) ) : ?>
                <?php \Royal_MCP\Admin\Settings_Page::render_founders_banner( false ); ?>
            <?php endif; ?>
        </div>
        <?php
    }

    /* ==================================================================
     *  5. Royal MCP Pro Founding Members — Chrome Pack card (P5a)
     * ================================================================ */

    /**
     * True on/after the hardcoded Pro launch date.
     */
    private function is_pro_launched(): bool {
        // Use site timezone rather than server for admin-facing UI consistency.
        $now       = current_datetime()->format( 'Y-m-d' );
        return $now >= self::PRO_LAUNCH_DATE;
    }

    /**
     * Compose the UTM-tagged URL for a given surface (chrome_pack, admin_notice,
     * admin_menu). Switches base URL depending on pre-/post-launch.
     *
     * @param array  $utm_parts    {source: string, content: string}
     * @param string $utm_campaign campaign identifier
     */
    private function pro_url_for( array $utm_parts, string $utm_campaign ): string {
        $base = $this->is_pro_launched() ? self::PRO_POST_LAUNCH_URL_BASE : self::PRO_WAITLIST_URL_BASE;
        return add_query_arg(
            array(
                'utm_source'   => $utm_parts['source'] ?? 'royal_mcp_free',
                'utm_medium'   => 'free_plugin',
                'utm_content'  => $utm_parts['content'] ?? 'founding_members',
                'utm_campaign' => $utm_campaign,
            ),
            $base
        );
    }

    /* ==================================================================
     *  6. Founding Members admin notice (P5b)
     * ================================================================ */

    /**
     * Admin notice pointing admins to the Pro waitlist. Version-stamped —
     * dismissal stores the current plugin version, and the notice re-appears
     * once on each plugin version update (same pattern as the Founders Bundle
     * banner). Pre-/post-launch content differs and uses separate dismiss keys
     * so a user who dismissed the pre-launch notice still sees the post-launch
     * one when Pro ships.
     */
    public function render_founding_members_notice(): void {
        if ( ! current_user_can( 'manage_options' ) ) {
            return;
        }
        $post_launch  = $this->is_pro_launched();
        $dismiss_meta = $post_launch ? self::PRO_LAUNCH_NOTICE_DISMISS_META : self::FM_NOTICE_DISMISS_META;
        $dismissed_at = get_user_meta( get_current_user_id(), $dismiss_meta, true );
        if ( $dismissed_at && version_compare( (string) $dismissed_at, ROYAL_MCP_VERSION, '>=' ) ) {
            return;
        }

        $url_args    = array(
            'source'  => 'admin_notice',
            'content' => $post_launch ? 'post_launch' : 'founding_members',
        );
        $campaign    = $post_launch ? '1438_postlaunch_notice' : 'waitlist_1438_notice';
        $cta_url     = $this->pro_url_for( $url_args, $campaign );
        $dismiss_url = wp_nonce_url(
            admin_url( 'admin-post.php?action=' . self::FM_NOTICE_DISMISS_ACTION . '&launched=' . ( $post_launch ? '1' : '0' ) ),
            self::FM_NOTICE_DISMISS_ACTION
        );
        ?>
        <div class="notice notice-info royal-mcp-fm-notice" style="padding: 14px 18px;">
            <p style="margin: 0 0 8px; font-size: 14px;">
                <strong>
                    <?php if ( $post_launch ) : ?>
                        &#127881; <?php esc_html_e( 'Royal MCP Pro is live!', 'royal-mcp' ); ?>
                    <?php else : ?>
                        &#127881; <?php esc_html_e( 'Royal MCP Pro launches Aug 25 — Join the Founding Members waitlist', 'royal-mcp' ); ?>
                    <?php endif; ?>
                </strong>
            </p>
            <p style="margin: 0 0 12px;">
                <?php if ( $post_launch ) : ?>
                    <?php esc_html_e( '220+ MCP tools. The Solo Dev & Agency Workflow — one chat runs every client site. Scoped endpoints per project, bulk ops across whole catalogs, and a 90-day audit log so you can show clients exactly what changed.', 'royal-mcp' ); ?>
                <?php else : ?>
                    <?php esc_html_e( 'Lock in $79/yr LIFETIME pricing (going to $149/yr after launch). Limited to 100 spots. No obligation until launch day.', 'royal-mcp' ); ?>
                <?php endif; ?>
            </p>
            <p style="margin: 0;">
                <a href="<?php echo esc_url( $cta_url ); ?>" target="_blank" rel="noopener noreferrer" class="button button-primary">
                    <?php if ( $post_launch ) : ?>
                        <?php esc_html_e( 'See Pro workflows &rarr;', 'royal-mcp' ); ?>
                    <?php else : ?>
                        <?php esc_html_e( 'Reserve My Spot &rarr;', 'royal-mcp' ); ?>
                    <?php endif; ?>
                </a>
                &nbsp;
                <a href="<?php echo esc_url( $dismiss_url ); ?>" style="margin-left: 6px;">
                    <?php esc_html_e( 'Dismiss', 'royal-mcp' ); ?>
                </a>
            </p>
        </div>
        <?php
    }

    public function handle_founding_members_dismiss(): void {
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( esc_html__( 'You do not have permission to dismiss this notice.', 'royal-mcp' ) );
        }
        check_admin_referer( self::FM_NOTICE_DISMISS_ACTION );
        // Which variant was dismissed? Query arg tells us.
        $launched     = ! empty( $_GET['launched'] );
        $dismiss_meta = $launched ? self::PRO_LAUNCH_NOTICE_DISMISS_META : self::FM_NOTICE_DISMISS_META;
        update_user_meta( get_current_user_id(), $dismiss_meta, ROYAL_MCP_VERSION );
        wp_safe_redirect( wp_get_referer() ?: admin_url() );
        exit;
    }

    /* ==================================================================
     *  7. Founding Members submenu item (P5c)
     * ================================================================ */

    /**
     * Register the Founding Members submenu under Royal MCP. Label switches
     * based on launch date. Uses a placeholder slug that inject_founding_members_menu_target_blank
     * rewrites in $submenu to the external URL + JS adds target=_blank.
     */
    public function register_founding_members_menu(): void {
        // Sidebar-length constraint: "Founding Members" doesn't fit — use short
        // "Founders" (matches existing Founders Bundle branding). Card + admin
        // notice still use the full "Founding Members" name where prose has room.
        $label = $this->is_pro_launched()
            ? '<span class="royal-mcp-upgrade-menu-text">' . esc_html__( 'Upgrade to Pro', 'royal-mcp' ) . '</span>'
            : '&#127873; ' . __( 'Founders', 'royal-mcp' );

        add_submenu_page(
            'royal-mcp',
            $this->is_pro_launched() ? __( 'Royal MCP Pro', 'royal-mcp' ) : __( 'Royal MCP Pro Founding Members', 'royal-mcp' ),
            $label,
            'manage_options',
            self::FM_MENU_SLUG,
            '__return_true'
        );

        // Rewrite the submenu's href in $submenu to the external URL. WP admin
        // submenu items are internal by convention; rewriting the URL directly
        // + adding target=_blank via JS below sends users out to the waitlist /
        // Pro landing without loading an intermediate WP admin page.
        global $submenu;
        if ( isset( $submenu['royal-mcp'] ) ) {
            $url_args = array(
                'source'  => 'admin_menu',
                'content' => $this->is_pro_launched() ? 'get_pro_menu' : 'founding_members_menu',
            );
            $campaign = $this->is_pro_launched() ? '1438_postlaunch_menu' : 'waitlist_1438_menu';
            $cta_url  = $this->pro_url_for( $url_args, $campaign );
            foreach ( $submenu['royal-mcp'] as $idx => $item ) {
                if ( isset( $item[2] ) && $item[2] === self::FM_MENU_SLUG ) {
                    $submenu['royal-mcp'][ $idx ][2] = $cta_url;
                }
            }
        }
    }

    /**
     * Add target="_blank" + rel="noopener noreferrer" to the Founding Members
     * submenu link. WordPress submenu API doesn't support link attributes natively;
     * a tiny JS shim finds the link by its royalplugins.com href pattern and
     * rewrites the attrs. Attached via wp_add_inline_script on the always-loaded
     * `common` handle for CSP-friendly delivery.
     */
    public function inject_founding_members_menu_target_blank(): void {
        if ( ! is_admin() ) {
            return;
        }
        $waitlist_host = wp_parse_url( self::PRO_WAITLIST_URL_BASE, PHP_URL_HOST );
        $post_host     = wp_parse_url( self::PRO_POST_LAUNCH_URL_BASE, PHP_URL_HOST );
        $js = sprintf(
            '(function(){var links=document.querySelectorAll("#adminmenu a");for(var i=0;i<links.length;i++){var href=links[i].getAttribute("href")||"";if(href.indexOf(%1$s)!==-1||href.indexOf(%2$s)!==-1){links[i].setAttribute("target","_blank");links[i].setAttribute("rel","noopener noreferrer");}}})();',
            wp_json_encode( '//' . $waitlist_host ),
            wp_json_encode( '//' . $post_host )
        );
        wp_add_inline_script( 'common', $js );
    }

    /* ==================================================================
     *  Family plugin registry
     * ================================================================ */

    private function get_family_plugins(): array {
        /**
         * Filter the Royal Tools plugin family list. Child plugins (e.g.
         * Royal MCP Pro when vendoring this codebase) can replace the free
         * companion set with a premium companion set. Each entry supports
         * the same keys used below plus two optional overrides:
         *   - install_url: custom URL for the "Get X" / "Install" button
         *     when the plugin isn't installed (defaults to WP.org search
         *     using search_slug when omitted)
         *   - badge_label: custom badge label like "PRO" (defaults to
         *     "FREE" when omitted)
         */
        return apply_filters( 'royal_mcp_chrome_tools_family', [
            'royal-ai-firewall' => [
                'name'        => __( 'Royal AI Firewall', 'royal-mcp' ),
                'basename'    => 'royal-ai-firewall/royal-ai-firewall.php',
                'icon'        => '&#128737;',
                'search_slug' => 'royal-ai-firewall',
                'learn_url'   => 'https://royalplugins.com/founders/',
                'pitch'       => __( 'See every AI agent hitting your site and decide who gets in. Blocks GPTBot, ClaudeBot, PerplexityBot and 60+ others at the WordPress layer.', 'royal-mcp' ),
            ],
            'royal-mcp' => [
                'name'        => __( 'Royal MCP', 'royal-mcp' ),
                'basename'    => 'royal-mcp/royal-mcp.php',
                'icon'        => '&#128268;',
                'search_slug' => 'royal-mcp',
                'learn_url'   => 'https://royalplugins.com/founders/',
                'pitch'       => __( 'Connect Claude, ChatGPT, and Cursor directly to your WordPress site via MCP. Full-stack tools for AI-driven content and store management.', 'royal-mcp' ),
            ],
            'sitevault' => [
                'name'        => __( 'SiteVault Lite', 'royal-mcp' ),
                'basename'    => 'sitevault-backup-restore-migration/sitevault.php',
                'icon'        => '&#128190;',
                'search_slug' => 'sitevault backup',
                'learn_url'   => 'https://royalplugins.com/founders/',
                'pitch'       => __( 'Full-site backup, restore, and migration in your WordPress admin. WP-CLI commands for automation. No cloud upsell, no seat limits.', 'royal-mcp' ),
            ],
            'royal-access' => [
                'name'        => __( 'Royal Access', 'royal-mcp' ),
                'basename'    => 'royal-access/royal-access.php',
                'icon'        => '&#9855;',
                'search_slug' => 'royal-access',
                'learn_url'   => 'https://royalplugins.com/founders/',
                'pitch'       => __( 'Accessibility toolbar, contrast checker, and WCAG-fix suggestions for your WordPress site. Every setting free.', 'royal-mcp' ),
            ],
            'royal-links' => [
                'name'        => __( 'Royal Links', 'royal-mcp' ),
                'basename'    => 'royal-links/royal-links.php',
                'icon'        => '&#128279;',
                'search_slug' => 'royal-links',
                'learn_url'   => 'https://royalplugins.com/founders/',
                'pitch'       => __( 'Link cloaking, click tracking, geo-targeting, A/B testing, QR codes, and 404 redirect manager.', 'royal-mcp' ),
            ],
        ] );
    }

    /**
     * Registry + per-card state (you're here / active / installed-inactive /
     * not installed). Loaded once per page render.
     */
    public function get_family_plugins_with_state(): array {
        if ( ! function_exists( 'get_plugins' ) ) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }
        $all_installed = array_keys( get_plugins() );
        $out           = $this->get_family_plugins();
        $current       = defined( 'ROYAL_MCP_PLUGIN_BASENAME' ) ? ROYAL_MCP_PLUGIN_BASENAME : 'royal-mcp/royal-mcp.php';
        foreach ( $out as $slug => &$plugin ) {
            if ( $plugin['basename'] === $current ) {
                $plugin['state'] = 'here';
            } elseif ( in_array( $plugin['basename'], $all_installed, true ) && is_plugin_active( $plugin['basename'] ) ) {
                $plugin['state'] = 'active';
            } elseif ( in_array( $plugin['basename'], $all_installed, true ) ) {
                $plugin['state'] = 'inactive';
            } else {
                $plugin['state'] = 'not_installed';
            }
        }
        return $out;
    }

    private function render_plugin_card( string $slug, array $plugin ): void {
        $state       = $plugin['state'] ?? 'not_installed';
        $card_class  = 'royal-mcp-tools-card';
        if ( 'here' === $state ) {
            $card_class .= ' royal-mcp-tools-card--here';
        } elseif ( 'active' === $state ) {
            $card_class .= ' royal-mcp-tools-card--active';
        }
        ?>
        <div class="<?php echo esc_attr( $card_class ); ?>">
            <div class="royal-mcp-tools-card-head">
                <div class="royal-mcp-tools-card-icon" aria-hidden="true"><?php echo wp_kses_post( $plugin['icon'] ); ?></div>
                <?php $this->render_card_badge( $state, $plugin ); ?>
            </div>
            <h3><?php echo esc_html( $plugin['name'] ); ?></h3>
            <p><?php echo esc_html( $plugin['pitch'] ); ?></p>
            <div class="royal-mcp-tools-card-actions">
                <?php $this->render_card_actions( $slug, $plugin ); ?>
            </div>
        </div>
        <?php
    }

    private function render_card_badge( string $state, array $plugin = [] ): void {
        if ( 'here' === $state ) {
            echo '<span class="royal-mcp-tools-card-badge">' . esc_html__( 'You\'re here', 'royal-mcp' ) . '</span>';
        } elseif ( 'active' === $state ) {
            echo '<span class="royal-mcp-tools-card-badge">' . esc_html__( '✓ Active', 'royal-mcp' ) . '</span>';
        } else {
            // Premium entries pass badge_label="PRO" so the tier reads correctly
            // in the tools grid. Falls back to FREE for the default WP.org family.
            $label = ! empty( $plugin['badge_label'] ) ? (string) $plugin['badge_label'] : __( 'FREE', 'royal-mcp' );
            echo '<span class="royal-mcp-tools-card-badge royal-mcp-tools-card-badge--free">' . esc_html( $label ) . '</span>';
        }
    }

    private function render_card_actions( string $slug, array $plugin ): void {
        $state = $plugin['state'] ?? 'not_installed';
        if ( 'here' === $state ) {
            echo '<div class="royal-mcp-tools-badge-active">' . esc_html__( 'You\'re here', 'royal-mcp' ) . '</div>';
            return;
        }
        if ( 'active' === $state ) {
            echo '<div class="royal-mcp-tools-badge-active">' . esc_html__( '✓ Active', 'royal-mcp' ) . '</div>';
            return;
        }
        if ( 'inactive' === $state ) {
            $activate_url = wp_nonce_url(
                admin_url( 'plugins.php?action=activate&plugin=' . urlencode( $plugin['basename'] ) ),
                'activate-plugin_' . $plugin['basename']
            );
            printf(
                '<a href="%1$s" class="royal-mcp-tools-btn-activate">%2$s</a><a href="%3$s" target="_blank" rel="noopener noreferrer" class="royal-mcp-tools-btn-learn">%4$s</a>',
                esc_url( $activate_url ),
                esc_html__( 'Activate', 'royal-mcp' ),
                esc_url( $plugin['learn_url'] ),
                esc_html__( 'Learn', 'royal-mcp' )
            );
            return;
        }
        // Premium entries carry a custom install_url pointing at their
        // purchase / pricing page, and open in a new tab. Free entries fall
        // back to the WP.org search screen in-admin.
        $is_premium  = ! empty( $plugin['install_url'] );
        $install_url = $is_premium
            ? (string) $plugin['install_url']
            : admin_url( 'plugin-install.php?s=' . rawurlencode( $plugin['search_slug'] ) . '&tab=search&type=term' );
        $install_label = $is_premium
            ? sprintf( __( 'Get %s', 'royal-mcp' ), $plugin['name'] )
            : __( 'Install', 'royal-mcp' );
        $install_target = $is_premium ? ' target="_blank" rel="noopener noreferrer"' : '';
        printf(
            '<a href="%1$s"%5$s class="royal-mcp-tools-btn-install">%2$s</a><a href="%3$s" target="_blank" rel="noopener noreferrer" class="royal-mcp-tools-btn-learn">%4$s</a>',
            esc_url( $install_url ),
            esc_html( $install_label ),
            esc_url( $plugin['learn_url'] ),
            esc_html__( 'Learn', 'royal-mcp' ),
            $install_target // safe: hardcoded string above
        );
    }
}
